"""The promotion board must be reproducible from the committed evidence.

The board this replaced could not be regenerated by anything in the repository:
its A-share row cited 44,750 events that appear in no committed file, and both
scripts that wrote ``data/promotion_board.json`` would have overwritten those
rows with a different experiment entirely. These tests make that failure mode
impossible to reintroduce silently.
"""

from __future__ import annotations

import json
from pathlib import Path


import numpy as np

from libs.quant.event_study_board import (
    EDGE_SPECS,
    MIN_CLUSTERS,
    MIN_OBSERVATIONS,
    EdgeSpec,
    Role,
    build_board,
    evaluate_spec,
)
from libs.quant.hypothesis import HypothesisRegistry
from libs.quant.promotion_registry import PromotionRegistry

BOARD_PATH = Path("data/promotion_board.json")


def test_committed_board_matches_the_evidence():
    """Regenerating from the raw result files must reproduce the board exactly.

    If this fails, either an experiment was re-run without regenerating the
    board, or a row was edited by hand. Both mean the gate no longer says what
    the data says.
    """
    board = json.loads(BOARD_PATH.read_text())
    rebuilt = build_board(HypothesisRegistry().n_trials)
    assert rebuilt == board, (
        "data/promotion_board.json is out of step with the experiment output — "
        "run: python scripts/event_study_board.py"
    )


def test_every_row_cites_a_source_that_exists():
    board = json.loads(BOARD_PATH.read_text())
    for row in board["board"]:
        assert row["source"], row
        assert Path(row["source"]).exists(), f"{row['strategy']} cites a missing file"


def test_every_row_has_an_explicit_role():
    """A row without a role gets no permission, so none may be left unlabelled."""
    board = json.loads(BOARD_PATH.read_text())
    for row in board["board"]:
        assert row["role"] in {Role.TRADE.value, Role.AVOID.value}, row


def test_tradable_rows_name_a_real_strategy():
    """The gap this project had: approved edges nothing could execute.

    A ``trade`` row grants permission to open a position, so a strategy with
    that id has to exist — otherwise the gate is protecting a desk that has no
    way to act on what it approved.

    An **empty** tradable list is not a failure. It is the board's current state:
    once the t-statistics were recomputed with clustered standard errors, both
    former trade rows dropped below the hurdle. A test that requires at least one
    tradable edge would turn "we found nothing this quarter" into a red build,
    and the pressure that creates is exactly how a marginal result gets promoted.
    """
    board = json.loads(BOARD_PATH.read_text())
    tradable = [r for r in board["board"] if r["approved"] and r["role"] == Role.TRADE.value]

    for row in tradable:
        config = Path("strategies") / row["strategy"] / "config.yaml"
        assert config.exists(), (
            f"{row['strategy']} is approved for trading but has no implementation "
            f"at {config}"
        )


def test_every_approved_row_used_clustered_inference():
    """No row may be approved on an i.i.d. t-statistic.

    This is the check that would have caught the original defect. Both trade
    edges cleared a 3.77 hurdle with t=5.40 and t=6.38 computed as
    ``mean / (sd / sqrt(n))`` — valid only if the events were independent, which
    for overlapping 20-session and 5-day holds they are not. Clustered, the same
    real data gives 2.35 and 1.81.
    """
    board = json.loads(BOARD_PATH.read_text())
    assert board["inference"] == "cluster_robust"
    for row in board["board"]:
        if not row["approved"]:
            continue
        assert row["inference"] == "cluster_robust", row["strategy"]
        assert row["n_clusters"] >= board["min_clusters"], row["strategy"]
        # The clustered statistic must be the one on the row, and it must be the
        # weaker of the two — if it exceeds the i.i.d. value, the clustering is
        # not doing what it claims.
        assert abs(row["t_stat"]) <= abs(row["t_stat_iid"]) + 1e-9, row["strategy"]


def test_a_source_without_per_event_data_cannot_be_approved():
    """Fail closed when the statistic cannot be verified.

    A result file that carries only a summary ``t_stat`` gives the board no way
    to check the standard error. That is the shape every result file had before
    this change, so accepting it would silently restore the flaw.
    """
    row = evaluate_spec(
        _SPEC, _payload(n=5000, mean_excess_pct=9.0, t_stat=42.0, win_rate=0.9), 35,
        _clean_manifest(),
    )
    assert row["approved"] is False
    assert row["failed"] == ["no_per_event_data_cannot_verify_t"]
    assert row["t_stat"] is None


def test_avoid_rows_never_grant_trade_permission():
    registry = PromotionRegistry(BOARD_PATH)
    board = json.loads(BOARD_PATH.read_text())
    for row in board["board"]:
        if row["role"] == Role.AVOID.value:
            assert registry.is_promoted(row["strategy"]) is False


def test_hurdle_is_recomputed_at_the_current_trial_count():
    """The board must not inherit the easier hurdle a raw file happened to use."""
    board = json.loads(BOARD_PATH.read_text())
    n_trials = HypothesisRegistry().n_trials
    assert board["n_trials"] == n_trials
    for row in board["board"]:
        assert row["t_hurdle"] == board["t_hurdle"]


# ------------------------------------------------------------- rule behaviour
_SPEC = EdgeSpec(
    strategy="demo", instrument="X", domain="us_equity", hypothesis_id="h",
    source="data/none.json", source_strategy="row", expected_sign=+1,
    role=Role.TRADE, implementation="long", max_evidence_age_days=90,
)


def _clean_manifest():
    """A reproducible run, so provenance is not what the test is measuring.

    Trade rows must cite a replayable run — a result nobody can reproduce is a
    claim. Tests about the *statistical* rules supply one so the two concerns stay
    separable; ``test_a_trade_row_without_a_manifest_is_refused`` covers the gate
    itself.
    """
    from libs.data import run_manifest

    m = run_manifest.pin("test")
    m.code = {"commit": "0" * 40, "dirty": False, "dirty_files": 0}
    m.inputs["synthetic"] = {
        "data_contract": {
            "dataset": "synthetic",
            "instrument": "symbol",
            "effective_at": "event_date",
            "observed_at": "fetched_at",
            "pit_level": "historical_point_in_time",
            "strict_historical_pit": True,
            "price_basis": "raw",
        }
    }
    return m


def test_trade_row_using_non_strict_pit_data_is_refused():
    manifest = _clean_manifest()
    manifest.inputs["synthetic"]["data_contract"]["strict_historical_pit"] = False
    row = evaluate_spec(
        _SPEC, _measured(1000, 0.04, 0.02, weeks=30), 4, manifest,
    )
    assert row["approved"] is False
    assert row["pit_status"] == "non_strict"
    assert "non_strict_pit_data_cannot_trade" in row["failed"]


def _payload(**row):
    return {"generated_at": "2026-01-01", "results": [{"strategy": "row", **row}]}


def _events(
    n: int, mean: float, sd: float, *, weeks: int, shock: float = 0.0,
    seed: int = 7, end_anchor=None,
):
    """Synthetic per-event returns spread over ``weeks`` distinct calendar weeks.

    ``shock`` is the standard deviation of a *per-week common component* — the
    thing that makes real event studies dependent. Events in the same week share
    a market move and, with a multi-day hold, literally share price path; that
    common term is what the i.i.d. formula ignores and what clustering recovers.
    With ``shock=0`` the events genuinely are independent and clustering
    correctly leaves the error alone, which is why the fixture has to be able to
    produce both cases.
    """
    import datetime as dt

    rng = np.random.default_rng(seed)
    # Anchor the window so it ends `weeks` back from today; otherwise every
    # fixture would age past the staleness limit as the calendar advances and the
    # suite would start failing on a date rather than on a defect.
    start = end_anchor or (
        dt.datetime.now(dt.UTC).date() - dt.timedelta(weeks=weeks + 1)
    )
    start -= dt.timedelta(days=start.weekday())   # snap to a Monday
    week_shock = rng.normal(0.0, shock, size=weeks) if shock else np.zeros(weeks)
    out = []
    for i in range(n):
        week = i % weeks
        date = start + dt.timedelta(weeks=week, days=i % 5)
        value = rng.normal(mean, sd) + float(week_shock[week])
        out.append({"date": date.isoformat(), "excess": value})
    return out


def _measured(
    n: int, mean: float, sd: float, *, weeks: int, shock: float = 0.0,
    hold_days: int = 5, end_anchor=None, **extra,
):
    """A payload whose verdict comes from real numbers rather than a claim."""
    return {
        "generated_at": "2026-01-01",
        "hold_days": hold_days,
        "results": [{
            "strategy": "row",
            "n": n,
            "mean_excess_pct": round(mean * 100, 3),
            "events": _events(n, mean, sd, weeks=weeks, shock=shock, end_anchor=end_anchor),
            **extra,
        }],
    }


def test_result_against_the_preregistered_direction_is_rejected():
    """A result with the opposite sign falsified the hypothesis.

    It is not a new edge pointing the other way — inventing one is the data
    snooping this project already caught itself doing once.
    """
    row = evaluate_spec(_SPEC, _measured(1000, -0.04, 0.05, weeks=40), 35, _clean_manifest())
    assert row["approved"] is False
    assert "wrong_sign_vs_preregistration" in row["failed"]


def test_underpowered_sample_is_rejected():
    row = evaluate_spec(_SPEC, _measured(50, 0.04, 0.02, weeks=25), 35, _clean_manifest())
    assert row["approved"] is False
    assert f"n<{MIN_OBSERVATIONS}" in row["failed"]


def test_events_crammed_into_few_weeks_are_rejected():
    """Raw count is not sample size when the events are dependent.

    1,000 events inside 6 weeks is six independent observations of the market
    wearing a large-n disguise. This is the altcoin edge's exact shape: 245
    events, 13 weeks.
    """
    row = evaluate_spec(_SPEC, _measured(1000, 0.03, 0.02, weeks=6), 35, _clean_manifest())
    assert row["approved"] is False
    assert f"independent_clusters<{MIN_CLUSTERS}" in row["failed"]
    assert row["n_clusters"] == 6


def test_clustering_widens_the_error_when_events_share_a_shock():
    """With a common weekly component, the corrected statistic must be smaller.

    This is the mechanism behind the real finding: the returns are unchanged, the
    mean is unchanged, and only the standard error moves — because the events
    were never the independent draws the i.i.d. formula assumed.
    """
    row = evaluate_spec(_SPEC, _measured(600, 0.02, 0.03, weeks=25, shock=0.04), 35, _clean_manifest())
    assert abs(row["t_stat"]) < abs(row["t_stat_iid"])


def test_clustering_is_neutral_on_genuinely_independent_events():
    """No penalty where there is no dependence — the fix must not be a blanket haircut.

    If clustering always shrank the statistic it would just be a tax, and a tax
    can be argued away. It has to be a measurement, which means it leaves clean
    data alone.
    """
    row = evaluate_spec(_SPEC, _measured(600, 0.02, 0.03, weeks=25, shock=0.0), 35, _clean_manifest())
    assert abs(row["t_stat"]) > abs(row["t_stat_iid"]) * 0.7


def test_more_trials_make_the_hurdle_harder():
    """The correction has to bite: the same result must fail at more trials."""
    # A clean, well-spread effect: strong enough to clear a lenient hurdle even
    # after clustering, so the trial count is what decides the verdict.
    # Calibrated to land between the two hurdles (clustered t ≈ 3.93 against 3.30
    # and 4.30), so the trial count alone flips the verdict.
    payload = _measured(1000, 0.008, 0.03, weeks=30, shock=0.004)
    easy = evaluate_spec(_SPEC, payload, 4, _clean_manifest())
    hard = evaluate_spec(_SPEC, payload, 400, _clean_manifest())
    assert easy["t_hurdle"] < hard["t_hurdle"]
    assert easy["approved"] is True
    assert hard["approved"] is False


def test_missing_row_is_not_an_approval():
    row = evaluate_spec(_SPEC, {"results": []}, 35)
    assert row["approved"] is False
    assert row["failed"] == ["no_result"]


def test_board_is_deterministic():
    """Same inputs, same bytes — otherwise ``--check`` could never be trusted."""
    first = build_board(35)
    second = build_board(35)
    assert json.dumps(first, sort_keys=True) == json.dumps(second, sort_keys=True)


def test_specs_are_in_scope():
    """Only the three in-scope instrument domains, per the project's own scope."""
    allowed = {"a_share", "us_equity", "altcoin", "btc_5m"}
    for spec in EDGE_SPECS:
        assert spec.domain in allowed, spec


# ------------------------------------------------------------- evidence ageing
def test_the_board_records_the_evidence_boundary_not_its_age():
    """The board must not hold a value that changes overnight.

    Storing ``evidence_age_days`` made ``approved`` drift on its own: the file was
    written on one day and failed to reproduce on the next, breaking the single
    guarantee the board offers. The boundary of the study is a fact and belongs
    here; how old that makes it is a question about today, answered at read time
    by :class:`libs.quant.promotion_registry.PromotionRecord`.
    """
    row = evaluate_spec(_SPEC, _measured(1000, 0.03, 0.01, weeks=30), 35, _clean_manifest())
    assert row["evidence_end"] is not None
    assert "evidence_age_days" not in row
    assert row["max_evidence_age_days"] == _SPEC.max_evidence_age_days


def test_the_board_is_stable_across_days():
    """Rebuilding tomorrow from the same evidence must give the same bytes."""
    import datetime as dt

    old = dt.date.today() - dt.timedelta(days=400)
    payload = _measured(1000, 0.03, 0.01, weeks=30, end_anchor=old)
    first = evaluate_spec(_SPEC, payload, 35, _clean_manifest())
    for value in first.values():
        assert not isinstance(value, dt.date)
    # Nothing on the row may encode "now".
    assert first["evidence_end"] == max(e["date"] for e in payload["results"][0]["events"])


def test_evidence_boundary_comes_from_the_last_event_not_the_run_timestamp():
    """Re-running a script over cached data must not refresh the evidence.

    ``generated_at`` says when the process ran. It moves every time anyone
    re-executes the experiment, including on identical cached inputs, so using it
    would let a stale edge look current with no new observations at all.
    """
    import datetime as dt

    old = dt.date.today() - dt.timedelta(days=400)
    payload = _measured(1000, 0.03, 0.01, weeks=30, end_anchor=old)
    payload["generated_at"] = dt.datetime.now(dt.UTC).isoformat()   # "fresh" run
    row = evaluate_spec(_SPEC, payload, 35, _clean_manifest())

    # The boundary tracks the last event (the window starts 400 days back and runs
    # 30 weeks forward), so it lands well outside the 90-day shelf life despite the
    # timestamp claiming the run happened seconds ago.
    boundary = dt.date.fromisoformat(row["evidence_end"])
    age = (dt.date.today() - boundary).days
    assert age > _SPEC.max_evidence_age_days, f"boundary {boundary} is only {age}d old"

    # And the runtime gate is what turns that age into a refusal.
    from libs.quant.promotion_registry import PromotionRecord

    record = PromotionRecord(
        strategy="demo", instrument="X", approved=True, role="trade",
        sharpe=0.0, dsr=None, failed=[],
        evidence_end=row["evidence_end"],
        max_evidence_age_days=row["max_evidence_age_days"],
    )
    assert record.evidence_expired is True
    assert record.tradable is False


def test_every_spec_declares_an_expiry():
    """No edge may default into an unlimited shelf life."""
    for spec in EDGE_SPECS:
        assert spec.max_evidence_age_days > 0, spec.strategy


def test_the_committed_board_carries_a_boundary_for_every_verifiable_row():
    """A row without per-event data has no boundary to report.

    ``btc5m_mispricing`` is that case: n=95 with no events, which is why it already
    fails on ``no_per_event_data_cannot_verify_t``. The field must still be present
    and explicitly null — absent would reach the dashboard as ``undefined``.
    """
    board = json.loads(BOARD_PATH.read_text())
    for row in board["board"]:
        assert "evidence_end" in row
        assert "max_evidence_age_days" in row
        if row["inference"] == "cluster_robust":
            assert row["evidence_end"] is not None, row["strategy"]


# ------------------------------------------------------------------ provenance
def test_a_trade_row_without_a_manifest_is_refused():
    """A result nobody can replay is a claim, not evidence.

    Every result file in this project once had this shape: no observation cut, no
    code state, no parameters. Re-running gave a different n. Permission to commit
    money cannot rest on that.
    """
    row = evaluate_spec(_SPEC, _measured(1000, 0.03, 0.01, weeks=30), 35, None)
    assert row["approved"] is False
    assert "no_run_manifest_cannot_replay" in row["failed"]


def test_a_trade_row_from_a_dirty_tree_is_refused():
    """The recorded commit does not describe what ran."""
    from libs.data import run_manifest

    m = run_manifest.pin("test")
    m.code = {"commit": "abc", "dirty": True, "dirty_files": 12}
    row = evaluate_spec(_SPEC, _measured(1000, 0.03, 0.01, weeks=30), 35, m)
    assert row["approved"] is False
    assert "run_not_reproducible_dirty_tree" in row["failed"]
    assert row["run_reproducible"] is False


def test_an_avoid_filter_does_not_need_a_manifest():
    """An avoidance filter only stops you buying; it commits no money.

    Holding it to the same provenance bar would delete the one finding that
    survived clustering, for a reason that does not apply to what it authorises.
    """
    spec = EdgeSpec(
        strategy="a", instrument="I", domain="a_share", hypothesis_id="h",
        source="data/none.json", source_strategy="row", expected_sign=-1,
        role=Role.AVOID, implementation="avoid_only", max_evidence_age_days=90,
    )
    row = evaluate_spec(spec, _measured(3000, -0.02, 0.02, weeks=120), 35, None)
    assert row["approved"] is True
    assert row["run_reproducible"] is None


# ------------------------------------------- what actually defends the gate
def test_the_hurdle_is_nearly_insensitive_to_the_trial_count():
    """Pinning a limitation, so nobody mistakes the hurdle for a search defence.

    ``3.0 + 0.5*log10(n_trials)`` is logarithmic. Registering a 16-configuration
    specification search moved the hurdle from 4.193 to 4.203 — two thousandths of a t.
    Going the other way, gutting the correction from 237 trials to 5 moves it only 4.19 to
    3.35. So the hurdle cannot price a forking-paths search, whatever its name suggests,
    and the guards that *do* bite are the cluster floor and out-of-sample behaviour.
    """
    from libs.quant.pbo import deflated_t_stat_threshold

    assert deflated_t_stat_threshold(255) - deflated_t_stat_threshold(243) < 0.02
    assert deflated_t_stat_threshold(237) - deflated_t_stat_threshold(5) < 0.9


def test_a_searched_pipeline_faces_a_higher_independence_bar():
    """The only real defence against a forking path is data the search never saw.

    ``insider_cluster_buy`` had its inference method, benchmark and weighting each chosen
    after seeing results on this sample — 16 available pipelines — and the sequence walked
    its t from 2.35 to 4.21. Every step has a prior justification; the sequence does not.
    So it must clear 30 independent units rather than 20, and the only way to get them is
    calendar.
    """
    from libs.quant.event_study_board import (
        MIN_CLUSTERS,
        SEARCHED_PIPELINE_MIN_CLUSTERS,
        SEARCHED_PIPELINES,
    )

    assert SEARCHED_PIPELINE_MIN_CLUSTERS > MIN_CLUSTERS
    assert "insider_cluster_buy" in SEARCHED_PIPELINES

    board = json.loads(BOARD_PATH.read_text())
    row = next(r for r in board["board"] if r["strategy"] == "us_insider_cluster_buy")
    assert row["pipeline_searched"] is True
    assert row["cluster_floor"] == SEARCHED_PIPELINE_MIN_CLUSTERS
    # It now clears the t-hurdle. The floor is the only thing holding it, which is the
    # honest state and the reason the floor exists.
    assert abs(row["t_stat"]) >= row["t_hurdle"]
    assert row["approved"] is False
    assert f"independent_clusters<{SEARCHED_PIPELINE_MIN_CLUSTERS}" in row["failed"]


def test_an_unsearched_pipeline_keeps_the_ordinary_floor():
    from libs.quant.event_study_board import MIN_CLUSTERS

    board = json.loads(BOARD_PATH.read_text())
    row = next(r for r in board["board"] if r["strategy"] == "a_share_billboard_reversal")
    assert row["pipeline_searched"] is False
    assert row["cluster_floor"] == MIN_CLUSTERS


def test_the_surviving_edge_holds_out_of_sample():
    """The only edge that changes behaviour, split in time.

    In-sample t=-4.16, out of sample t=-5.97 — stronger out of sample, which is the
    opposite of overfitting. If this ever inverts, the filter should stop being applied
    before anyone argues about why.
    """
    board = json.loads(BOARD_PATH.read_text())
    row = next(r for r in board["board"] if r["strategy"] == "a_share_billboard_reversal")
    oos = row["out_of_sample"]
    assert oos["available"] is True
    assert oos["sign_held"] is True
    assert oos["t_ratio"] > 1.0
